spring.application.name=HireTrackBackend
spring.datasource.url=jdbc:postgresql://localhost:5432/hiretrackbackend
spring.datasource.username=postgres
spring.datasource.password=Kripa@123
spring.flyway.enabled=true
server.port=8080
logging.level.org.springframework.security=DEBUG

jwt.secret=c2VjcmV0S2V5Rm9ySGlyZVRyYWNrQmFja2VuZEpXVFRva2VuU2lnbmluZzIwMjY=
jwt.expiration=86400000


spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.upload.dir=./uploads/resumes