/*
 * This file is generated by jOOQ.
 */
package com.example.hiretrack.jooq.tables;


import com.example.hiretrack.jooq.Indexes;
import com.example.hiretrack.jooq.Keys;
import com.example.hiretrack.jooq.Public;
import com.example.hiretrack.jooq.tables.CandidateDocuments.CandidateDocumentsPath;
import com.example.hiretrack.jooq.tables.Interviews.InterviewsPath;
import com.example.hiretrack.jooq.tables.JobOpenings.JobOpeningsPath;
import com.example.hiretrack.jooq.tables.Users.UsersPath;
import com.example.hiretrack.jooq.tables.records.CandidatesRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Candidates extends TableImpl<CandidatesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.candidates</code>
     */
    public static final Candidates CANDIDATES = new Candidates();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CandidatesRecord> getRecordType() {
        return CandidatesRecord.class;
    }

    /**
     * The column <code>public.candidates.id</code>.
     */
    public final TableField<CandidatesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.candidates.full_name</code>.
     */
    public final TableField<CandidatesRecord, String> FULL_NAME = createField(DSL.name("full_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.candidates.email</code>.
     */
    public final TableField<CandidatesRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.candidates.phone</code>.
     */
    public final TableField<CandidatesRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.candidates.experience_years</code>.
     */
    public final TableField<CandidatesRecord, BigDecimal> EXPERIENCE_YEARS = createField(DSL.name("experience_years"), SQLDataType.NUMERIC(4, 1), this, "");

    /**
     * The column <code>public.candidates.job_id</code>.
     */
    public final TableField<CandidatesRecord, Long> JOB_ID = createField(DSL.name("job_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.candidates.status</code>.
     */
    public final TableField<CandidatesRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(30).nullable(false).defaultValue(DSL.field(DSL.raw("'APPLIED'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.candidates.added_by</code>.
     */
    public final TableField<CandidatesRecord, Long> ADDED_BY = createField(DSL.name("added_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.candidates.created_at</code>.
     */
    public final TableField<CandidatesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.candidates.updated_at</code>.
     */
    public final TableField<CandidatesRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private Candidates(Name alias, Table<CandidatesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Candidates(Name alias, Table<CandidatesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.candidates</code> table reference
     */
    public Candidates(String alias) {
        this(DSL.name(alias), CANDIDATES);
    }

    /**
     * Create an aliased <code>public.candidates</code> table reference
     */
    public Candidates(Name alias) {
        this(alias, CANDIDATES);
    }

    /**
     * Create a <code>public.candidates</code> table reference
     */
    public Candidates() {
        this(DSL.name("candidates"), null);
    }

    public <O extends Record> Candidates(Table<O> path, ForeignKey<O, CandidatesRecord> childPath, InverseForeignKey<O, CandidatesRecord> parentPath) {
        super(path, childPath, parentPath, CANDIDATES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CandidatesPath extends Candidates implements Path<CandidatesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CandidatesPath(Table<O> path, ForeignKey<O, CandidatesRecord> childPath, InverseForeignKey<O, CandidatesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CandidatesPath(Name alias, Table<CandidatesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CandidatesPath as(String alias) {
            return new CandidatesPath(DSL.name(alias), this);
        }

        @Override
        public CandidatesPath as(Name alias) {
            return new CandidatesPath(alias, this);
        }

        @Override
        public CandidatesPath as(Table<?> alias) {
            return new CandidatesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CANDIDATES_JOB);
    }

    @Override
    public Identity<CandidatesRecord, Long> getIdentity() {
        return (Identity<CandidatesRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CandidatesRecord> getPrimaryKey() {
        return Keys.CANDIDATES_PKEY;
    }

    @Override
    public List<UniqueKey<CandidatesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CANDIDATES_EMAIL_KEY);
    }

    @Override
    public List<ForeignKey<CandidatesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CANDIDATES__CANDIDATES_ADDED_BY_FKEY, Keys.CANDIDATES__CANDIDATES_JOB_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.CANDIDATES__CANDIDATES_ADDED_BY_FKEY, null);

        return _users;
    }

    private transient JobOpeningsPath _jobOpenings;

    /**
     * Get the implicit join path to the <code>public.job_openings</code> table.
     */
    public JobOpeningsPath jobOpenings() {
        if (_jobOpenings == null)
            _jobOpenings = new JobOpeningsPath(this, Keys.CANDIDATES__CANDIDATES_JOB_ID_FKEY, null);

        return _jobOpenings;
    }

    private transient CandidateDocumentsPath _candidateDocuments;

    /**
     * Get the implicit to-many join path to the
     * <code>public.candidate_documents</code> table
     */
    public CandidateDocumentsPath candidateDocuments() {
        if (_candidateDocuments == null)
            _candidateDocuments = new CandidateDocumentsPath(this, null, Keys.CANDIDATE_DOCUMENTS__CANDIDATE_DOCUMENTS_CANDIDATE_ID_FKEY.getInverseKey());

        return _candidateDocuments;
    }

    private transient InterviewsPath _interviews;

    /**
     * Get the implicit to-many join path to the <code>public.interviews</code>
     * table
     */
    public InterviewsPath interviews() {
        if (_interviews == null)
            _interviews = new InterviewsPath(this, null, Keys.INTERVIEWS__INTERVIEWS_CANDIDATE_ID_FKEY.getInverseKey());

        return _interviews;
    }

    @Override
    public List<Check<CandidatesRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("candidates_status_check"), "(((status)::text = ANY ((ARRAY['APPLIED'::character varying, 'SHORTLISTED'::character varying, 'INTERVIEW_SCHEDULED'::character varying, 'SELECTED'::character varying, 'REJECTED'::character varying])::text[])))", true)
        );
    }

    @Override
    public Candidates as(String alias) {
        return new Candidates(DSL.name(alias), this);
    }

    @Override
    public Candidates as(Name alias) {
        return new Candidates(alias, this);
    }

    @Override
    public Candidates as(Table<?> alias) {
        return new Candidates(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Candidates rename(String name) {
        return new Candidates(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Candidates rename(Name name) {
        return new Candidates(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Candidates rename(Table<?> name) {
        return new Candidates(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Candidates where(Condition condition) {
        return new Candidates(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Candidates where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Candidates where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Candidates where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Candidates where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Candidates where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Candidates where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Candidates where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Candidates whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Candidates whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
