/*
 * This file is generated by jOOQ.
 */
package com.example.hiretrack.jooq.tables;


import com.example.hiretrack.jooq.Keys;
import com.example.hiretrack.jooq.Public;
import com.example.hiretrack.jooq.tables.Candidates.CandidatesPath;
import com.example.hiretrack.jooq.tables.Users.UsersPath;
import com.example.hiretrack.jooq.tables.records.CandidateDocumentsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CandidateDocuments extends TableImpl<CandidateDocumentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.candidate_documents</code>
     */
    public static final CandidateDocuments CANDIDATE_DOCUMENTS = new CandidateDocuments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CandidateDocumentsRecord> getRecordType() {
        return CandidateDocumentsRecord.class;
    }

    /**
     * The column <code>public.candidate_documents.id</code>.
     */
    public final TableField<CandidateDocumentsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.candidate_documents.candidate_id</code>.
     */
    public final TableField<CandidateDocumentsRecord, Long> CANDIDATE_ID = createField(DSL.name("candidate_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.candidate_documents.file_name</code>.
     */
    public final TableField<CandidateDocumentsRecord, String> FILE_NAME = createField(DSL.name("file_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.candidate_documents.file_path</code>.
     */
    public final TableField<CandidateDocumentsRecord, String> FILE_PATH = createField(DSL.name("file_path"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>public.candidate_documents.uploaded_by</code>.
     */
    public final TableField<CandidateDocumentsRecord, Long> UPLOADED_BY = createField(DSL.name("uploaded_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.candidate_documents.uploaded_at</code>.
     */
    public final TableField<CandidateDocumentsRecord, LocalDateTime> UPLOADED_AT = createField(DSL.name("uploaded_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private CandidateDocuments(Name alias, Table<CandidateDocumentsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CandidateDocuments(Name alias, Table<CandidateDocumentsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.candidate_documents</code> table reference
     */
    public CandidateDocuments(String alias) {
        this(DSL.name(alias), CANDIDATE_DOCUMENTS);
    }

    /**
     * Create an aliased <code>public.candidate_documents</code> table reference
     */
    public CandidateDocuments(Name alias) {
        this(alias, CANDIDATE_DOCUMENTS);
    }

    /**
     * Create a <code>public.candidate_documents</code> table reference
     */
    public CandidateDocuments() {
        this(DSL.name("candidate_documents"), null);
    }

    public <O extends Record> CandidateDocuments(Table<O> path, ForeignKey<O, CandidateDocumentsRecord> childPath, InverseForeignKey<O, CandidateDocumentsRecord> parentPath) {
        super(path, childPath, parentPath, CANDIDATE_DOCUMENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CandidateDocumentsPath extends CandidateDocuments implements Path<CandidateDocumentsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CandidateDocumentsPath(Table<O> path, ForeignKey<O, CandidateDocumentsRecord> childPath, InverseForeignKey<O, CandidateDocumentsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CandidateDocumentsPath(Name alias, Table<CandidateDocumentsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CandidateDocumentsPath as(String alias) {
            return new CandidateDocumentsPath(DSL.name(alias), this);
        }

        @Override
        public CandidateDocumentsPath as(Name alias) {
            return new CandidateDocumentsPath(alias, this);
        }

        @Override
        public CandidateDocumentsPath as(Table<?> alias) {
            return new CandidateDocumentsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CandidateDocumentsRecord, Long> getIdentity() {
        return (Identity<CandidateDocumentsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CandidateDocumentsRecord> getPrimaryKey() {
        return Keys.CANDIDATE_DOCUMENTS_PKEY;
    }

    @Override
    public List<ForeignKey<CandidateDocumentsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CANDIDATE_DOCUMENTS__CANDIDATE_DOCUMENTS_CANDIDATE_ID_FKEY, Keys.CANDIDATE_DOCUMENTS__CANDIDATE_DOCUMENTS_UPLOADED_BY_FKEY);
    }

    private transient CandidatesPath _candidates;

    /**
     * Get the implicit join path to the <code>public.candidates</code> table.
     */
    public CandidatesPath candidates() {
        if (_candidates == null)
            _candidates = new CandidatesPath(this, Keys.CANDIDATE_DOCUMENTS__CANDIDATE_DOCUMENTS_CANDIDATE_ID_FKEY, null);

        return _candidates;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.CANDIDATE_DOCUMENTS__CANDIDATE_DOCUMENTS_UPLOADED_BY_FKEY, null);

        return _users;
    }

    @Override
    public CandidateDocuments as(String alias) {
        return new CandidateDocuments(DSL.name(alias), this);
    }

    @Override
    public CandidateDocuments as(Name alias) {
        return new CandidateDocuments(alias, this);
    }

    @Override
    public CandidateDocuments as(Table<?> alias) {
        return new CandidateDocuments(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CandidateDocuments rename(String name) {
        return new CandidateDocuments(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CandidateDocuments rename(Name name) {
        return new CandidateDocuments(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CandidateDocuments rename(Table<?> name) {
        return new CandidateDocuments(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CandidateDocuments where(Condition condition) {
        return new CandidateDocuments(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CandidateDocuments where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CandidateDocuments where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CandidateDocuments where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CandidateDocuments where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CandidateDocuments where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CandidateDocuments where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CandidateDocuments where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CandidateDocuments whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CandidateDocuments whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
