/*
 * This file is generated by jOOQ.
 */
package com.example.hiretrack.jooq.tables;


import com.example.hiretrack.jooq.Indexes;
import com.example.hiretrack.jooq.Keys;
import com.example.hiretrack.jooq.Public;
import com.example.hiretrack.jooq.tables.Candidates.CandidatesPath;
import com.example.hiretrack.jooq.tables.InterviewFeedback.InterviewFeedbackPath;
import com.example.hiretrack.jooq.tables.JobOpenings.JobOpeningsPath;
import com.example.hiretrack.jooq.tables.Users.UsersPath;
import com.example.hiretrack.jooq.tables.records.InterviewsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Interviews extends TableImpl<InterviewsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.interviews</code>
     */
    public static final Interviews INTERVIEWS = new Interviews();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InterviewsRecord> getRecordType() {
        return InterviewsRecord.class;
    }

    /**
     * The column <code>public.interviews.id</code>.
     */
    public final TableField<InterviewsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.interviews.candidate_id</code>.
     */
    public final TableField<InterviewsRecord, Long> CANDIDATE_ID = createField(DSL.name("candidate_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.interviews.job_id</code>.
     */
    public final TableField<InterviewsRecord, Long> JOB_ID = createField(DSL.name("job_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.interviews.interviewer_id</code>.
     */
    public final TableField<InterviewsRecord, Long> INTERVIEWER_ID = createField(DSL.name("interviewer_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.interviews.scheduled_at</code>.
     */
    public final TableField<InterviewsRecord, LocalDateTime> SCHEDULED_AT = createField(DSL.name("scheduled_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.interviews.duration_minutes</code>.
     */
    public final TableField<InterviewsRecord, Integer> DURATION_MINUTES = createField(DSL.name("duration_minutes"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("45"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.interviews.status</code>.
     */
    public final TableField<InterviewsRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false).defaultValue(DSL.field(DSL.raw("'SCHEDULED'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.interviews.created_by</code>.
     */
    public final TableField<InterviewsRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.interviews.created_at</code>.
     */
    public final TableField<InterviewsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.interviews.updated_at</code>.
     */
    public final TableField<InterviewsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private Interviews(Name alias, Table<InterviewsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Interviews(Name alias, Table<InterviewsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.interviews</code> table reference
     */
    public Interviews(String alias) {
        this(DSL.name(alias), INTERVIEWS);
    }

    /**
     * Create an aliased <code>public.interviews</code> table reference
     */
    public Interviews(Name alias) {
        this(alias, INTERVIEWS);
    }

    /**
     * Create a <code>public.interviews</code> table reference
     */
    public Interviews() {
        this(DSL.name("interviews"), null);
    }

    public <O extends Record> Interviews(Table<O> path, ForeignKey<O, InterviewsRecord> childPath, InverseForeignKey<O, InterviewsRecord> parentPath) {
        super(path, childPath, parentPath, INTERVIEWS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class InterviewsPath extends Interviews implements Path<InterviewsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> InterviewsPath(Table<O> path, ForeignKey<O, InterviewsRecord> childPath, InverseForeignKey<O, InterviewsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private InterviewsPath(Name alias, Table<InterviewsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public InterviewsPath as(String alias) {
            return new InterviewsPath(DSL.name(alias), this);
        }

        @Override
        public InterviewsPath as(Name alias) {
            return new InterviewsPath(alias, this);
        }

        @Override
        public InterviewsPath as(Table<?> alias) {
            return new InterviewsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_INTERVIEWS_INTERVIEWER);
    }

    @Override
    public Identity<InterviewsRecord, Long> getIdentity() {
        return (Identity<InterviewsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<InterviewsRecord> getPrimaryKey() {
        return Keys.INTERVIEWS_PKEY;
    }

    @Override
    public List<ForeignKey<InterviewsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.INTERVIEWS__INTERVIEWS_CANDIDATE_ID_FKEY, Keys.INTERVIEWS__INTERVIEWS_CREATED_BY_FKEY, Keys.INTERVIEWS__INTERVIEWS_INTERVIEWER_ID_FKEY, Keys.INTERVIEWS__INTERVIEWS_JOB_ID_FKEY);
    }

    private transient CandidatesPath _candidates;

    /**
     * Get the implicit join path to the <code>public.candidates</code> table.
     */
    public CandidatesPath candidates() {
        if (_candidates == null)
            _candidates = new CandidatesPath(this, Keys.INTERVIEWS__INTERVIEWS_CANDIDATE_ID_FKEY, null);

        return _candidates;
    }

    private transient UsersPath _interviewsCreatedByFkey;

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>interviews_created_by_fkey</code> key.
     */
    public UsersPath interviewsCreatedByFkey() {
        if (_interviewsCreatedByFkey == null)
            _interviewsCreatedByFkey = new UsersPath(this, Keys.INTERVIEWS__INTERVIEWS_CREATED_BY_FKEY, null);

        return _interviewsCreatedByFkey;
    }

    private transient UsersPath _interviewsInterviewerIdFkey;

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>interviews_interviewer_id_fkey</code> key.
     */
    public UsersPath interviewsInterviewerIdFkey() {
        if (_interviewsInterviewerIdFkey == null)
            _interviewsInterviewerIdFkey = new UsersPath(this, Keys.INTERVIEWS__INTERVIEWS_INTERVIEWER_ID_FKEY, null);

        return _interviewsInterviewerIdFkey;
    }

    private transient JobOpeningsPath _jobOpenings;

    /**
     * Get the implicit join path to the <code>public.job_openings</code> table.
     */
    public JobOpeningsPath jobOpenings() {
        if (_jobOpenings == null)
            _jobOpenings = new JobOpeningsPath(this, Keys.INTERVIEWS__INTERVIEWS_JOB_ID_FKEY, null);

        return _jobOpenings;
    }

    private transient InterviewFeedbackPath _interviewFeedback;

    /**
     * Get the implicit to-many join path to the
     * <code>public.interview_feedback</code> table
     */
    public InterviewFeedbackPath interviewFeedback() {
        if (_interviewFeedback == null)
            _interviewFeedback = new InterviewFeedbackPath(this, null, Keys.INTERVIEW_FEEDBACK__INTERVIEW_FEEDBACK_INTERVIEW_ID_FKEY.getInverseKey());

        return _interviewFeedback;
    }

    @Override
    public List<Check<InterviewsRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("interviews_status_check"), "(((status)::text = ANY ((ARRAY['SCHEDULED'::character varying, 'RESCHEDULED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying])::text[])))", true)
        );
    }

    @Override
    public Interviews as(String alias) {
        return new Interviews(DSL.name(alias), this);
    }

    @Override
    public Interviews as(Name alias) {
        return new Interviews(alias, this);
    }

    @Override
    public Interviews as(Table<?> alias) {
        return new Interviews(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Interviews rename(String name) {
        return new Interviews(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Interviews rename(Name name) {
        return new Interviews(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Interviews rename(Table<?> name) {
        return new Interviews(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Interviews where(Condition condition) {
        return new Interviews(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Interviews where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Interviews where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Interviews where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Interviews where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Interviews where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Interviews where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Interviews where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Interviews whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Interviews whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
