/*
 * This file is generated by jOOQ.
 */
package com.example.hiretrack.jooq.tables;


import com.example.hiretrack.jooq.Keys;
import com.example.hiretrack.jooq.Public;
import com.example.hiretrack.jooq.tables.Interviews.InterviewsPath;
import com.example.hiretrack.jooq.tables.Users.UsersPath;
import com.example.hiretrack.jooq.tables.records.InterviewFeedbackRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InterviewFeedback extends TableImpl<InterviewFeedbackRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.interview_feedback</code>
     */
    public static final InterviewFeedback INTERVIEW_FEEDBACK = new InterviewFeedback();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InterviewFeedbackRecord> getRecordType() {
        return InterviewFeedbackRecord.class;
    }

    /**
     * The column <code>public.interview_feedback.id</code>.
     */
    public final TableField<InterviewFeedbackRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.interview_feedback.interview_id</code>.
     */
    public final TableField<InterviewFeedbackRecord, Long> INTERVIEW_ID = createField(DSL.name("interview_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.interview_feedback.technical_rating</code>.
     */
    public final TableField<InterviewFeedbackRecord, Integer> TECHNICAL_RATING = createField(DSL.name("technical_rating"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.interview_feedback.communication_rating</code>.
     */
    public final TableField<InterviewFeedbackRecord, Integer> COMMUNICATION_RATING = createField(DSL.name("communication_rating"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.interview_feedback.recommendation</code>.
     */
    public final TableField<InterviewFeedbackRecord, String> RECOMMENDATION = createField(DSL.name("recommendation"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>public.interview_feedback.comments</code>.
     */
    public final TableField<InterviewFeedbackRecord, String> COMMENTS = createField(DSL.name("comments"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.interview_feedback.submitted_by</code>.
     */
    public final TableField<InterviewFeedbackRecord, Long> SUBMITTED_BY = createField(DSL.name("submitted_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.interview_feedback.submitted_at</code>.
     */
    public final TableField<InterviewFeedbackRecord, LocalDateTime> SUBMITTED_AT = createField(DSL.name("submitted_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private InterviewFeedback(Name alias, Table<InterviewFeedbackRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private InterviewFeedback(Name alias, Table<InterviewFeedbackRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.interview_feedback</code> table reference
     */
    public InterviewFeedback(String alias) {
        this(DSL.name(alias), INTERVIEW_FEEDBACK);
    }

    /**
     * Create an aliased <code>public.interview_feedback</code> table reference
     */
    public InterviewFeedback(Name alias) {
        this(alias, INTERVIEW_FEEDBACK);
    }

    /**
     * Create a <code>public.interview_feedback</code> table reference
     */
    public InterviewFeedback() {
        this(DSL.name("interview_feedback"), null);
    }

    public <O extends Record> InterviewFeedback(Table<O> path, ForeignKey<O, InterviewFeedbackRecord> childPath, InverseForeignKey<O, InterviewFeedbackRecord> parentPath) {
        super(path, childPath, parentPath, INTERVIEW_FEEDBACK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class InterviewFeedbackPath extends InterviewFeedback implements Path<InterviewFeedbackRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> InterviewFeedbackPath(Table<O> path, ForeignKey<O, InterviewFeedbackRecord> childPath, InverseForeignKey<O, InterviewFeedbackRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private InterviewFeedbackPath(Name alias, Table<InterviewFeedbackRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public InterviewFeedbackPath as(String alias) {
            return new InterviewFeedbackPath(DSL.name(alias), this);
        }

        @Override
        public InterviewFeedbackPath as(Name alias) {
            return new InterviewFeedbackPath(alias, this);
        }

        @Override
        public InterviewFeedbackPath as(Table<?> alias) {
            return new InterviewFeedbackPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<InterviewFeedbackRecord, Long> getIdentity() {
        return (Identity<InterviewFeedbackRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<InterviewFeedbackRecord> getPrimaryKey() {
        return Keys.INTERVIEW_FEEDBACK_PKEY;
    }

    @Override
    public List<UniqueKey<InterviewFeedbackRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.INTERVIEW_FEEDBACK_INTERVIEW_ID_KEY);
    }

    @Override
    public List<ForeignKey<InterviewFeedbackRecord, ?>> getReferences() {
        return Arrays.asList(Keys.INTERVIEW_FEEDBACK__INTERVIEW_FEEDBACK_INTERVIEW_ID_FKEY, Keys.INTERVIEW_FEEDBACK__INTERVIEW_FEEDBACK_SUBMITTED_BY_FKEY);
    }

    private transient InterviewsPath _interviews;

    /**
     * Get the implicit join path to the <code>public.interviews</code> table.
     */
    public InterviewsPath interviews() {
        if (_interviews == null)
            _interviews = new InterviewsPath(this, Keys.INTERVIEW_FEEDBACK__INTERVIEW_FEEDBACK_INTERVIEW_ID_FKEY, null);

        return _interviews;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.INTERVIEW_FEEDBACK__INTERVIEW_FEEDBACK_SUBMITTED_BY_FKEY, null);

        return _users;
    }

    @Override
    public List<Check<InterviewFeedbackRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("interview_feedback_communication_rating_check"), "(((communication_rating >= 1) AND (communication_rating <= 5)))", true),
            Internal.createCheck(this, DSL.name("interview_feedback_recommendation_check"), "(((recommendation)::text = ANY ((ARRAY['SELECT'::character varying, 'REJECT'::character varying, 'HOLD'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("interview_feedback_technical_rating_check"), "(((technical_rating >= 1) AND (technical_rating <= 5)))", true)
        );
    }

    @Override
    public InterviewFeedback as(String alias) {
        return new InterviewFeedback(DSL.name(alias), this);
    }

    @Override
    public InterviewFeedback as(Name alias) {
        return new InterviewFeedback(alias, this);
    }

    @Override
    public InterviewFeedback as(Table<?> alias) {
        return new InterviewFeedback(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public InterviewFeedback rename(String name) {
        return new InterviewFeedback(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InterviewFeedback rename(Name name) {
        return new InterviewFeedback(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public InterviewFeedback rename(Table<?> name) {
        return new InterviewFeedback(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InterviewFeedback where(Condition condition) {
        return new InterviewFeedback(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InterviewFeedback where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InterviewFeedback where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InterviewFeedback where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InterviewFeedback where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InterviewFeedback where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InterviewFeedback where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InterviewFeedback where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InterviewFeedback whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InterviewFeedback whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
