/*
 * This file is generated by jOOQ.
 */
package com.example.hiretrack.jooq.tables;


import com.example.hiretrack.jooq.Keys;
import com.example.hiretrack.jooq.Public;
import com.example.hiretrack.jooq.tables.Candidates.CandidatesPath;
import com.example.hiretrack.jooq.tables.Interviews.InterviewsPath;
import com.example.hiretrack.jooq.tables.Users.UsersPath;
import com.example.hiretrack.jooq.tables.records.JobOpeningsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JobOpenings extends TableImpl<JobOpeningsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.job_openings</code>
     */
    public static final JobOpenings JOB_OPENINGS = new JobOpenings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JobOpeningsRecord> getRecordType() {
        return JobOpeningsRecord.class;
    }

    /**
     * The column <code>public.job_openings.id</code>.
     */
    public final TableField<JobOpeningsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.job_openings.title</code>.
     */
    public final TableField<JobOpeningsRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.job_openings.description</code>.
     */
    public final TableField<JobOpeningsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.job_openings.department</code>.
     */
    public final TableField<JobOpeningsRecord, String> DEPARTMENT = createField(DSL.name("department"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.job_openings.status</code>.
     */
    public final TableField<JobOpeningsRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false).defaultValue(DSL.field(DSL.raw("'OPEN'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.job_openings.created_by</code>.
     */
    public final TableField<JobOpeningsRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.job_openings.created_at</code>.
     */
    public final TableField<JobOpeningsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.job_openings.updated_at</code>.
     */
    public final TableField<JobOpeningsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private JobOpenings(Name alias, Table<JobOpeningsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private JobOpenings(Name alias, Table<JobOpeningsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.job_openings</code> table reference
     */
    public JobOpenings(String alias) {
        this(DSL.name(alias), JOB_OPENINGS);
    }

    /**
     * Create an aliased <code>public.job_openings</code> table reference
     */
    public JobOpenings(Name alias) {
        this(alias, JOB_OPENINGS);
    }

    /**
     * Create a <code>public.job_openings</code> table reference
     */
    public JobOpenings() {
        this(DSL.name("job_openings"), null);
    }

    public <O extends Record> JobOpenings(Table<O> path, ForeignKey<O, JobOpeningsRecord> childPath, InverseForeignKey<O, JobOpeningsRecord> parentPath) {
        super(path, childPath, parentPath, JOB_OPENINGS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class JobOpeningsPath extends JobOpenings implements Path<JobOpeningsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> JobOpeningsPath(Table<O> path, ForeignKey<O, JobOpeningsRecord> childPath, InverseForeignKey<O, JobOpeningsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private JobOpeningsPath(Name alias, Table<JobOpeningsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public JobOpeningsPath as(String alias) {
            return new JobOpeningsPath(DSL.name(alias), this);
        }

        @Override
        public JobOpeningsPath as(Name alias) {
            return new JobOpeningsPath(alias, this);
        }

        @Override
        public JobOpeningsPath as(Table<?> alias) {
            return new JobOpeningsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<JobOpeningsRecord, Long> getIdentity() {
        return (Identity<JobOpeningsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<JobOpeningsRecord> getPrimaryKey() {
        return Keys.JOB_OPENINGS_PKEY;
    }

    @Override
    public List<ForeignKey<JobOpeningsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.JOB_OPENINGS__JOB_OPENINGS_CREATED_BY_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.JOB_OPENINGS__JOB_OPENINGS_CREATED_BY_FKEY, null);

        return _users;
    }

    private transient CandidatesPath _candidates;

    /**
     * Get the implicit to-many join path to the <code>public.candidates</code>
     * table
     */
    public CandidatesPath candidates() {
        if (_candidates == null)
            _candidates = new CandidatesPath(this, null, Keys.CANDIDATES__CANDIDATES_JOB_ID_FKEY.getInverseKey());

        return _candidates;
    }

    private transient InterviewsPath _interviews;

    /**
     * Get the implicit to-many join path to the <code>public.interviews</code>
     * table
     */
    public InterviewsPath interviews() {
        if (_interviews == null)
            _interviews = new InterviewsPath(this, null, Keys.INTERVIEWS__INTERVIEWS_JOB_ID_FKEY.getInverseKey());

        return _interviews;
    }

    @Override
    public List<Check<JobOpeningsRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("job_openings_status_check"), "(((status)::text = ANY ((ARRAY['OPEN'::character varying, 'ON_HOLD'::character varying, 'CLOSED'::character varying])::text[])))", true)
        );
    }

    @Override
    public JobOpenings as(String alias) {
        return new JobOpenings(DSL.name(alias), this);
    }

    @Override
    public JobOpenings as(Name alias) {
        return new JobOpenings(alias, this);
    }

    @Override
    public JobOpenings as(Table<?> alias) {
        return new JobOpenings(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JobOpenings rename(String name) {
        return new JobOpenings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JobOpenings rename(Name name) {
        return new JobOpenings(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JobOpenings rename(Table<?> name) {
        return new JobOpenings(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobOpenings where(Condition condition) {
        return new JobOpenings(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobOpenings where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobOpenings where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobOpenings where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JobOpenings where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JobOpenings where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JobOpenings where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JobOpenings where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobOpenings whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobOpenings whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
