/*
 * This file is generated by jOOQ.
 */
package com.example.hiretrack.jooq.tables;


import com.example.hiretrack.jooq.Keys;
import com.example.hiretrack.jooq.Public;
import com.example.hiretrack.jooq.tables.CandidateDocuments.CandidateDocumentsPath;
import com.example.hiretrack.jooq.tables.Candidates.CandidatesPath;
import com.example.hiretrack.jooq.tables.InterviewFeedback.InterviewFeedbackPath;
import com.example.hiretrack.jooq.tables.Interviews.InterviewsPath;
import com.example.hiretrack.jooq.tables.JobOpenings.JobOpeningsPath;
import com.example.hiretrack.jooq.tables.records.UsersRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Users extends TableImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.users</code>
     */
    public static final Users USERS = new Users();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsersRecord> getRecordType() {
        return UsersRecord.class;
    }

    /**
     * The column <code>public.users.id</code>.
     */
    public final TableField<UsersRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.users.email</code>.
     */
    public final TableField<UsersRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.users.password_hash</code>.
     */
    public final TableField<UsersRecord, String> PASSWORD_HASH = createField(DSL.name("password_hash"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.users.full_name</code>.
     */
    public final TableField<UsersRecord, String> FULL_NAME = createField(DSL.name("full_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.users.role</code>.
     */
    public final TableField<UsersRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.users.active</code>.
     */
    public final TableField<UsersRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.users.created_at</code>.
     */
    public final TableField<UsersRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.users.updated_at</code>.
     */
    public final TableField<UsersRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private Users(Name alias, Table<UsersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Users(Name alias, Table<UsersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.users</code> table reference
     */
    public Users(String alias) {
        this(DSL.name(alias), USERS);
    }

    /**
     * Create an aliased <code>public.users</code> table reference
     */
    public Users(Name alias) {
        this(alias, USERS);
    }

    /**
     * Create a <code>public.users</code> table reference
     */
    public Users() {
        this(DSL.name("users"), null);
    }

    public <O extends Record> Users(Table<O> path, ForeignKey<O, UsersRecord> childPath, InverseForeignKey<O, UsersRecord> parentPath) {
        super(path, childPath, parentPath, USERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UsersPath extends Users implements Path<UsersRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UsersPath(Table<O> path, ForeignKey<O, UsersRecord> childPath, InverseForeignKey<O, UsersRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UsersPath(Name alias, Table<UsersRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UsersPath as(String alias) {
            return new UsersPath(DSL.name(alias), this);
        }

        @Override
        public UsersPath as(Name alias) {
            return new UsersPath(alias, this);
        }

        @Override
        public UsersPath as(Table<?> alias) {
            return new UsersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<UsersRecord, Long> getIdentity() {
        return (Identity<UsersRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<UsersRecord> getPrimaryKey() {
        return Keys.USERS_PKEY;
    }

    @Override
    public List<UniqueKey<UsersRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.USERS_EMAIL_KEY);
    }

    private transient CandidateDocumentsPath _candidateDocuments;

    /**
     * Get the implicit to-many join path to the
     * <code>public.candidate_documents</code> table
     */
    public CandidateDocumentsPath candidateDocuments() {
        if (_candidateDocuments == null)
            _candidateDocuments = new CandidateDocumentsPath(this, null, Keys.CANDIDATE_DOCUMENTS__CANDIDATE_DOCUMENTS_UPLOADED_BY_FKEY.getInverseKey());

        return _candidateDocuments;
    }

    private transient CandidatesPath _candidates;

    /**
     * Get the implicit to-many join path to the <code>public.candidates</code>
     * table
     */
    public CandidatesPath candidates() {
        if (_candidates == null)
            _candidates = new CandidatesPath(this, null, Keys.CANDIDATES__CANDIDATES_ADDED_BY_FKEY.getInverseKey());

        return _candidates;
    }

    private transient InterviewFeedbackPath _interviewFeedback;

    /**
     * Get the implicit to-many join path to the
     * <code>public.interview_feedback</code> table
     */
    public InterviewFeedbackPath interviewFeedback() {
        if (_interviewFeedback == null)
            _interviewFeedback = new InterviewFeedbackPath(this, null, Keys.INTERVIEW_FEEDBACK__INTERVIEW_FEEDBACK_SUBMITTED_BY_FKEY.getInverseKey());

        return _interviewFeedback;
    }

    private transient InterviewsPath _interviewsCreatedByFkey;

    /**
     * Get the implicit to-many join path to the <code>public.interviews</code>
     * table, via the <code>interviews_created_by_fkey</code> key
     */
    public InterviewsPath interviewsCreatedByFkey() {
        if (_interviewsCreatedByFkey == null)
            _interviewsCreatedByFkey = new InterviewsPath(this, null, Keys.INTERVIEWS__INTERVIEWS_CREATED_BY_FKEY.getInverseKey());

        return _interviewsCreatedByFkey;
    }

    private transient InterviewsPath _interviewsInterviewerIdFkey;

    /**
     * Get the implicit to-many join path to the <code>public.interviews</code>
     * table, via the <code>interviews_interviewer_id_fkey</code> key
     */
    public InterviewsPath interviewsInterviewerIdFkey() {
        if (_interviewsInterviewerIdFkey == null)
            _interviewsInterviewerIdFkey = new InterviewsPath(this, null, Keys.INTERVIEWS__INTERVIEWS_INTERVIEWER_ID_FKEY.getInverseKey());

        return _interviewsInterviewerIdFkey;
    }

    private transient JobOpeningsPath _jobOpenings;

    /**
     * Get the implicit to-many join path to the
     * <code>public.job_openings</code> table
     */
    public JobOpeningsPath jobOpenings() {
        if (_jobOpenings == null)
            _jobOpenings = new JobOpeningsPath(this, null, Keys.JOB_OPENINGS__JOB_OPENINGS_CREATED_BY_FKEY.getInverseKey());

        return _jobOpenings;
    }

    @Override
    public List<Check<UsersRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("users_role_check"), "(((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'RECRUITER'::character varying, 'INTERVIEWER'::character varying])::text[])))", true)
        );
    }

    @Override
    public Users as(String alias) {
        return new Users(DSL.name(alias), this);
    }

    @Override
    public Users as(Name alias) {
        return new Users(alias, this);
    }

    @Override
    public Users as(Table<?> alias) {
        return new Users(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Users rename(String name) {
        return new Users(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Users rename(Name name) {
        return new Users(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Users rename(Table<?> name) {
        return new Users(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users where(Condition condition) {
        return new Users(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Users where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Users where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Users where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Users where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
