/*
 * This file is generated by jOOQ.
 */
package com.example.hiretrack.jooq.tables.records;


import com.example.hiretrack.jooq.tables.Candidates;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CandidatesRecord extends UpdatableRecordImpl<CandidatesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.candidates.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.candidates.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.candidates.full_name</code>.
     */
    public void setFullName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.candidates.full_name</code>.
     */
    public String getFullName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.candidates.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.candidates.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.candidates.phone</code>.
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.candidates.phone</code>.
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.candidates.experience_years</code>.
     */
    public void setExperienceYears(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.candidates.experience_years</code>.
     */
    public BigDecimal getExperienceYears() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>public.candidates.job_id</code>.
     */
    public void setJobId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.candidates.job_id</code>.
     */
    public Long getJobId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.candidates.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.candidates.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.candidates.added_by</code>.
     */
    public void setAddedBy(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.candidates.added_by</code>.
     */
    public Long getAddedBy() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.candidates.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.candidates.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.candidates.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.candidates.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CandidatesRecord
     */
    public CandidatesRecord() {
        super(Candidates.CANDIDATES);
    }

    /**
     * Create a detached, initialised CandidatesRecord
     */
    public CandidatesRecord(Long id, String fullName, String email, String phone, BigDecimal experienceYears, Long jobId, String status, Long addedBy, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Candidates.CANDIDATES);

        setId(id);
        setFullName(fullName);
        setEmail(email);
        setPhone(phone);
        setExperienceYears(experienceYears);
        setJobId(jobId);
        setStatus(status);
        setAddedBy(addedBy);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
