/*
 * This file is generated by jOOQ.
 */
package com.example.hiretrack.jooq.tables.records;


import com.example.hiretrack.jooq.tables.CandidateDocuments;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CandidateDocumentsRecord extends UpdatableRecordImpl<CandidateDocumentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.candidate_documents.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.candidate_documents.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.candidate_documents.candidate_id</code>.
     */
    public void setCandidateId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.candidate_documents.candidate_id</code>.
     */
    public Long getCandidateId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.candidate_documents.file_name</code>.
     */
    public void setFileName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.candidate_documents.file_name</code>.
     */
    public String getFileName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.candidate_documents.file_path</code>.
     */
    public void setFilePath(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.candidate_documents.file_path</code>.
     */
    public String getFilePath() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.candidate_documents.uploaded_by</code>.
     */
    public void setUploadedBy(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.candidate_documents.uploaded_by</code>.
     */
    public Long getUploadedBy() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.candidate_documents.uploaded_at</code>.
     */
    public void setUploadedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.candidate_documents.uploaded_at</code>.
     */
    public LocalDateTime getUploadedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CandidateDocumentsRecord
     */
    public CandidateDocumentsRecord() {
        super(CandidateDocuments.CANDIDATE_DOCUMENTS);
    }

    /**
     * Create a detached, initialised CandidateDocumentsRecord
     */
    public CandidateDocumentsRecord(Long id, Long candidateId, String fileName, String filePath, Long uploadedBy, LocalDateTime uploadedAt) {
        super(CandidateDocuments.CANDIDATE_DOCUMENTS);

        setId(id);
        setCandidateId(candidateId);
        setFileName(fileName);
        setFilePath(filePath);
        setUploadedBy(uploadedBy);
        setUploadedAt(uploadedAt);
        resetChangedOnNotNull();
    }
}
