/*
 * This file is generated by jOOQ.
 */
package com.example.hiretrack.jooq.tables.records;


import com.example.hiretrack.jooq.tables.InterviewFeedback;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InterviewFeedbackRecord extends UpdatableRecordImpl<InterviewFeedbackRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.interview_feedback.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.interview_feedback.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.interview_feedback.interview_id</code>.
     */
    public void setInterviewId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.interview_feedback.interview_id</code>.
     */
    public Long getInterviewId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.interview_feedback.technical_rating</code>.
     */
    public void setTechnicalRating(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.interview_feedback.technical_rating</code>.
     */
    public Integer getTechnicalRating() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.interview_feedback.communication_rating</code>.
     */
    public void setCommunicationRating(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.interview_feedback.communication_rating</code>.
     */
    public Integer getCommunicationRating() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.interview_feedback.recommendation</code>.
     */
    public void setRecommendation(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.interview_feedback.recommendation</code>.
     */
    public String getRecommendation() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.interview_feedback.comments</code>.
     */
    public void setComments(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.interview_feedback.comments</code>.
     */
    public String getComments() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.interview_feedback.submitted_by</code>.
     */
    public void setSubmittedBy(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.interview_feedback.submitted_by</code>.
     */
    public Long getSubmittedBy() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.interview_feedback.submitted_at</code>.
     */
    public void setSubmittedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.interview_feedback.submitted_at</code>.
     */
    public LocalDateTime getSubmittedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InterviewFeedbackRecord
     */
    public InterviewFeedbackRecord() {
        super(InterviewFeedback.INTERVIEW_FEEDBACK);
    }

    /**
     * Create a detached, initialised InterviewFeedbackRecord
     */
    public InterviewFeedbackRecord(Long id, Long interviewId, Integer technicalRating, Integer communicationRating, String recommendation, String comments, Long submittedBy, LocalDateTime submittedAt) {
        super(InterviewFeedback.INTERVIEW_FEEDBACK);

        setId(id);
        setInterviewId(interviewId);
        setTechnicalRating(technicalRating);
        setCommunicationRating(communicationRating);
        setRecommendation(recommendation);
        setComments(comments);
        setSubmittedBy(submittedBy);
        setSubmittedAt(submittedAt);
        resetChangedOnNotNull();
    }
}
