/*
 * This file is generated by jOOQ.
 */
package com.example.hiretrack.jooq.tables.records;


import com.example.hiretrack.jooq.tables.Interviews;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InterviewsRecord extends UpdatableRecordImpl<InterviewsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.interviews.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.interviews.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.interviews.candidate_id</code>.
     */
    public void setCandidateId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.interviews.candidate_id</code>.
     */
    public Long getCandidateId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.interviews.job_id</code>.
     */
    public void setJobId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.interviews.job_id</code>.
     */
    public Long getJobId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.interviews.interviewer_id</code>.
     */
    public void setInterviewerId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.interviews.interviewer_id</code>.
     */
    public Long getInterviewerId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.interviews.scheduled_at</code>.
     */
    public void setScheduledAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.interviews.scheduled_at</code>.
     */
    public LocalDateTime getScheduledAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.interviews.duration_minutes</code>.
     */
    public void setDurationMinutes(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.interviews.duration_minutes</code>.
     */
    public Integer getDurationMinutes() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.interviews.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.interviews.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.interviews.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.interviews.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.interviews.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.interviews.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.interviews.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.interviews.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InterviewsRecord
     */
    public InterviewsRecord() {
        super(Interviews.INTERVIEWS);
    }

    /**
     * Create a detached, initialised InterviewsRecord
     */
    public InterviewsRecord(Long id, Long candidateId, Long jobId, Long interviewerId, LocalDateTime scheduledAt, Integer durationMinutes, String status, Long createdBy, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Interviews.INTERVIEWS);

        setId(id);
        setCandidateId(candidateId);
        setJobId(jobId);
        setInterviewerId(interviewerId);
        setScheduledAt(scheduledAt);
        setDurationMinutes(durationMinutes);
        setStatus(status);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
