/*
 * This file is generated by jOOQ.
 */
package com.example.hiretrack.jooq.tables.records;


import com.example.hiretrack.jooq.tables.JobOpenings;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JobOpeningsRecord extends UpdatableRecordImpl<JobOpeningsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.job_openings.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.job_openings.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.job_openings.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.job_openings.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.job_openings.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.job_openings.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.job_openings.department</code>.
     */
    public void setDepartment(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.job_openings.department</code>.
     */
    public String getDepartment() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.job_openings.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.job_openings.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.job_openings.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.job_openings.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.job_openings.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.job_openings.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.job_openings.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.job_openings.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobOpeningsRecord
     */
    public JobOpeningsRecord() {
        super(JobOpenings.JOB_OPENINGS);
    }

    /**
     * Create a detached, initialised JobOpeningsRecord
     */
    public JobOpeningsRecord(Long id, String title, String description, String department, String status, Long createdBy, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(JobOpenings.JOB_OPENINGS);

        setId(id);
        setTitle(title);
        setDescription(description);
        setDepartment(department);
        setStatus(status);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
