/*
 * This file is generated by jOOQ.
 */
package com.example.hiretrack.jooq;


import com.example.hiretrack.jooq.tables.Candidates;
import com.example.hiretrack.jooq.tables.FlywaySchemaHistory;
import com.example.hiretrack.jooq.tables.Interviews;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index IDX_CANDIDATES_JOB = Internal.createIndex(DSL.name("idx_candidates_job"), Candidates.CANDIDATES, new OrderField[] { Candidates.CANDIDATES.JOB_ID }, false);
    public static final Index IDX_INTERVIEWS_INTERVIEWER = Internal.createIndex(DSL.name("idx_interviews_interviewer"), Interviews.INTERVIEWS, new OrderField[] { Interviews.INTERVIEWS.INTERVIEWER_ID, Interviews.INTERVIEWS.SCHEDULED_AT }, false);
}
