/*
 * This file is generated by jOOQ.
 */
package com.example.hiretrack.jooq;


import com.example.hiretrack.jooq.tables.CandidateDocuments;
import com.example.hiretrack.jooq.tables.Candidates;
import com.example.hiretrack.jooq.tables.FlywaySchemaHistory;
import com.example.hiretrack.jooq.tables.InterviewFeedback;
import com.example.hiretrack.jooq.tables.Interviews;
import com.example.hiretrack.jooq.tables.JobOpenings;
import com.example.hiretrack.jooq.tables.Users;
import com.example.hiretrack.jooq.tables.records.CandidateDocumentsRecord;
import com.example.hiretrack.jooq.tables.records.CandidatesRecord;
import com.example.hiretrack.jooq.tables.records.FlywaySchemaHistoryRecord;
import com.example.hiretrack.jooq.tables.records.InterviewFeedbackRecord;
import com.example.hiretrack.jooq.tables.records.InterviewsRecord;
import com.example.hiretrack.jooq.tables.records.JobOpeningsRecord;
import com.example.hiretrack.jooq.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CandidateDocumentsRecord> CANDIDATE_DOCUMENTS_PKEY = Internal.createUniqueKey(CandidateDocuments.CANDIDATE_DOCUMENTS, DSL.name("candidate_documents_pkey"), new TableField[] { CandidateDocuments.CANDIDATE_DOCUMENTS.ID }, true);
    public static final UniqueKey<CandidatesRecord> CANDIDATES_EMAIL_KEY = Internal.createUniqueKey(Candidates.CANDIDATES, DSL.name("candidates_email_key"), new TableField[] { Candidates.CANDIDATES.EMAIL }, true);
    public static final UniqueKey<CandidatesRecord> CANDIDATES_PKEY = Internal.createUniqueKey(Candidates.CANDIDATES, DSL.name("candidates_pkey"), new TableField[] { Candidates.CANDIDATES.ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<InterviewFeedbackRecord> INTERVIEW_FEEDBACK_INTERVIEW_ID_KEY = Internal.createUniqueKey(InterviewFeedback.INTERVIEW_FEEDBACK, DSL.name("interview_feedback_interview_id_key"), new TableField[] { InterviewFeedback.INTERVIEW_FEEDBACK.INTERVIEW_ID }, true);
    public static final UniqueKey<InterviewFeedbackRecord> INTERVIEW_FEEDBACK_PKEY = Internal.createUniqueKey(InterviewFeedback.INTERVIEW_FEEDBACK, DSL.name("interview_feedback_pkey"), new TableField[] { InterviewFeedback.INTERVIEW_FEEDBACK.ID }, true);
    public static final UniqueKey<InterviewsRecord> INTERVIEWS_PKEY = Internal.createUniqueKey(Interviews.INTERVIEWS, DSL.name("interviews_pkey"), new TableField[] { Interviews.INTERVIEWS.ID }, true);
    public static final UniqueKey<JobOpeningsRecord> JOB_OPENINGS_PKEY = Internal.createUniqueKey(JobOpenings.JOB_OPENINGS, DSL.name("job_openings_pkey"), new TableField[] { JobOpenings.JOB_OPENINGS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_EMAIL_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_email_key"), new TableField[] { Users.USERS.EMAIL }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CandidateDocumentsRecord, CandidatesRecord> CANDIDATE_DOCUMENTS__CANDIDATE_DOCUMENTS_CANDIDATE_ID_FKEY = Internal.createForeignKey(CandidateDocuments.CANDIDATE_DOCUMENTS, DSL.name("candidate_documents_candidate_id_fkey"), new TableField[] { CandidateDocuments.CANDIDATE_DOCUMENTS.CANDIDATE_ID }, Keys.CANDIDATES_PKEY, new TableField[] { Candidates.CANDIDATES.ID }, true);
    public static final ForeignKey<CandidateDocumentsRecord, UsersRecord> CANDIDATE_DOCUMENTS__CANDIDATE_DOCUMENTS_UPLOADED_BY_FKEY = Internal.createForeignKey(CandidateDocuments.CANDIDATE_DOCUMENTS, DSL.name("candidate_documents_uploaded_by_fkey"), new TableField[] { CandidateDocuments.CANDIDATE_DOCUMENTS.UPLOADED_BY }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<CandidatesRecord, UsersRecord> CANDIDATES__CANDIDATES_ADDED_BY_FKEY = Internal.createForeignKey(Candidates.CANDIDATES, DSL.name("candidates_added_by_fkey"), new TableField[] { Candidates.CANDIDATES.ADDED_BY }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<CandidatesRecord, JobOpeningsRecord> CANDIDATES__CANDIDATES_JOB_ID_FKEY = Internal.createForeignKey(Candidates.CANDIDATES, DSL.name("candidates_job_id_fkey"), new TableField[] { Candidates.CANDIDATES.JOB_ID }, Keys.JOB_OPENINGS_PKEY, new TableField[] { JobOpenings.JOB_OPENINGS.ID }, true);
    public static final ForeignKey<InterviewFeedbackRecord, InterviewsRecord> INTERVIEW_FEEDBACK__INTERVIEW_FEEDBACK_INTERVIEW_ID_FKEY = Internal.createForeignKey(InterviewFeedback.INTERVIEW_FEEDBACK, DSL.name("interview_feedback_interview_id_fkey"), new TableField[] { InterviewFeedback.INTERVIEW_FEEDBACK.INTERVIEW_ID }, Keys.INTERVIEWS_PKEY, new TableField[] { Interviews.INTERVIEWS.ID }, true);
    public static final ForeignKey<InterviewFeedbackRecord, UsersRecord> INTERVIEW_FEEDBACK__INTERVIEW_FEEDBACK_SUBMITTED_BY_FKEY = Internal.createForeignKey(InterviewFeedback.INTERVIEW_FEEDBACK, DSL.name("interview_feedback_submitted_by_fkey"), new TableField[] { InterviewFeedback.INTERVIEW_FEEDBACK.SUBMITTED_BY }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<InterviewsRecord, CandidatesRecord> INTERVIEWS__INTERVIEWS_CANDIDATE_ID_FKEY = Internal.createForeignKey(Interviews.INTERVIEWS, DSL.name("interviews_candidate_id_fkey"), new TableField[] { Interviews.INTERVIEWS.CANDIDATE_ID }, Keys.CANDIDATES_PKEY, new TableField[] { Candidates.CANDIDATES.ID }, true);
    public static final ForeignKey<InterviewsRecord, UsersRecord> INTERVIEWS__INTERVIEWS_CREATED_BY_FKEY = Internal.createForeignKey(Interviews.INTERVIEWS, DSL.name("interviews_created_by_fkey"), new TableField[] { Interviews.INTERVIEWS.CREATED_BY }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<InterviewsRecord, UsersRecord> INTERVIEWS__INTERVIEWS_INTERVIEWER_ID_FKEY = Internal.createForeignKey(Interviews.INTERVIEWS, DSL.name("interviews_interviewer_id_fkey"), new TableField[] { Interviews.INTERVIEWS.INTERVIEWER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<InterviewsRecord, JobOpeningsRecord> INTERVIEWS__INTERVIEWS_JOB_ID_FKEY = Internal.createForeignKey(Interviews.INTERVIEWS, DSL.name("interviews_job_id_fkey"), new TableField[] { Interviews.INTERVIEWS.JOB_ID }, Keys.JOB_OPENINGS_PKEY, new TableField[] { JobOpenings.JOB_OPENINGS.ID }, true);
    public static final ForeignKey<JobOpeningsRecord, UsersRecord> JOB_OPENINGS__JOB_OPENINGS_CREATED_BY_FKEY = Internal.createForeignKey(JobOpenings.JOB_OPENINGS, DSL.name("job_openings_created_by_fkey"), new TableField[] { JobOpenings.JOB_OPENINGS.CREATED_BY }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
}
