/*
 * This file is generated by jOOQ.
 */
package com.example.hiretrack.jooq;


import com.example.hiretrack.jooq.tables.CandidateDocuments;
import com.example.hiretrack.jooq.tables.Candidates;
import com.example.hiretrack.jooq.tables.FlywaySchemaHistory;
import com.example.hiretrack.jooq.tables.InterviewFeedback;
import com.example.hiretrack.jooq.tables.Interviews;
import com.example.hiretrack.jooq.tables.JobOpenings;
import com.example.hiretrack.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.candidate_documents</code>.
     */
    public final CandidateDocuments CANDIDATE_DOCUMENTS = CandidateDocuments.CANDIDATE_DOCUMENTS;

    /**
     * The table <code>public.candidates</code>.
     */
    public final Candidates CANDIDATES = Candidates.CANDIDATES;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.interview_feedback</code>.
     */
    public final InterviewFeedback INTERVIEW_FEEDBACK = InterviewFeedback.INTERVIEW_FEEDBACK;

    /**
     * The table <code>public.interviews</code>.
     */
    public final Interviews INTERVIEWS = Interviews.INTERVIEWS;

    /**
     * The table <code>public.job_openings</code>.
     */
    public final JobOpenings JOB_OPENINGS = JobOpenings.JOB_OPENINGS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CandidateDocuments.CANDIDATE_DOCUMENTS,
            Candidates.CANDIDATES,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            InterviewFeedback.INTERVIEW_FEEDBACK,
            Interviews.INTERVIEWS,
            JobOpenings.JOB_OPENINGS,
            Users.USERS
        );
    }
}
