/*
 * This file is generated by jOOQ.
 */
package com.example.hiretrack.jooq;


import com.example.hiretrack.jooq.tables.CandidateDocuments;
import com.example.hiretrack.jooq.tables.Candidates;
import com.example.hiretrack.jooq.tables.FlywaySchemaHistory;
import com.example.hiretrack.jooq.tables.InterviewFeedback;
import com.example.hiretrack.jooq.tables.Interviews;
import com.example.hiretrack.jooq.tables.JobOpenings;
import com.example.hiretrack.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.candidate_documents</code>.
     */
    public static final CandidateDocuments CANDIDATE_DOCUMENTS = CandidateDocuments.CANDIDATE_DOCUMENTS;

    /**
     * The table <code>public.candidates</code>.
     */
    public static final Candidates CANDIDATES = Candidates.CANDIDATES;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.interview_feedback</code>.
     */
    public static final InterviewFeedback INTERVIEW_FEEDBACK = InterviewFeedback.INTERVIEW_FEEDBACK;

    /**
     * The table <code>public.interviews</code>.
     */
    public static final Interviews INTERVIEWS = Interviews.INTERVIEWS;

    /**
     * The table <code>public.job_openings</code>.
     */
    public static final JobOpenings JOB_OPENINGS = JobOpenings.JOB_OPENINGS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
